### ISSUE TITLE
TODO List du TP

### ISSUE THREAD

**Issue by Heartbroken-Git** [Heartbroken-Git/Travaux-Pratiques-X6I0050#1]
A faire pour le rendu du TP3 :
# Questions du TP3
- [x] Question 1
  - [x] Faire les tables
  - [x] a)
  - [x] b)
  - [x] c)
- [x] Question 2
  - [x] Ecrire le trigger
  - [x] Expliquer en commentaire ou sur le readme l'erreur ```ORA-04091 : table ... is mutating``` (normale, c'était le but de la question)
- [x] Question 3
- [x] Question 4
- [x] Question 5
  - [x] Version Bloc PL/SQL
  - [x] Version procédure
- [x] Question 6

# Autres
- [x] Rédaction du readme
