### ISSUE TITLE
TODO List du TP5

### ISSUE THREAD

**Issue by Heartbroken-Git** [Heartbroken-Git/Travaux-Pratiques-X6I0050#2]
A faire pour le rendu du TP5 :
# Questions du TP5

## Prise en main de la table
- [x] Question 1
- [x] Question 2
## Visualisation du plan d'exécution d'une requête
- [x] Question 1
  - [x] Rédaction du fichier de génération des plan d'exécution
  - [x] Fichier de log des plans d'exécution générés et vérifiés
- [x] Question 2
  - [x] Rédaction du fichier de génération des plan d'exécution
  - [x] Fichier de log des plans d'exécution générés et vérifiés
- ~~Question 3~~ (pseudo optionnelle)
## Les index
- [ ] Question 1
- [ ] Question 2
  - [ ] Question 2.1
  - [ ] Question 2.2

# Autres
- [ ] Rédaction du readme
